networks:
  backend:
    driver: bridge

services:
  backend-db:
    image: postgres:latest
    container_name: anotaai-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      PGDATA: /tmp
      POSTGRES_DB: anotaai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - "./docker/data/db-backend:/var/lib/postgresql/data"
    networks:
      - backend

  # backend:
  #   build: .
  #   container_name: anotaai-backend
  #   env_file:
  #     - .env
  #   ports:
  #     - "3000:3000"
  #     - "4000:4000"
  #   extra_hosts:
  #     - "host.docker.internal:172.17.0.1"
  #   depends_on:
  #     backend-db:
  #       condition: service_healthy
  #   networks:
  #     - backend
